"""
Qdrant Configuration Module for LennyHub RAG

This module provides centralized configuration for Qdrant vector database.
It handles environment variable loading, connection testing, and fallback
to NanoVectorDB if Qdrant is unavailable.

Usage:
    from qdrant_config import get_lightrag_kwargs

    lightrag_kwargs = get_lightrag_kwargs()
    rag = RAGAnything(
        config=config,
        llm_model_func=llm_model_func,
        embedding_func=embedding_func,
        lightrag_kwargs=lightrag_kwargs
    )
"""

import os
from typing import Optional, Dict, Any
from dotenv import load_dotenv

# Load environment variables
load_dotenv()


def test_qdrant_connection(url: str) -> bool:
    """
    Test if Qdrant server is accessible.

    Args:
        url: Qdrant server URL (e.g., http://localhost:6333)

    Returns:
        True if connection successful, False otherwise
    """
    try:
        from qdrant_client import QdrantClient

        client = QdrantClient(url=url, timeout=5)
        # Try to get collections (will fail if server not accessible)
        client.get_collections()
        return True
    except Exception as e:
        print(f"Warning: Cannot connect to Qdrant at {url}: {e}")
        return False


def get_lightrag_kwargs(
    use_qdrant: Optional[bool] = None,
    qdrant_url: Optional[str] = None,
    multimodal: bool = False,
    verbose: bool = True
) -> Dict[str, Any]:
    """
    Get LightRAG configuration kwargs for vector database.

    Args:
        use_qdrant: Override USE_QDRANT env var (True/False/None for auto)
        qdrant_url: Override QDRANT_URL env var
        multimodal: If True, configure for multimodal (text + image) vectors
        verbose: Print configuration info

    Returns:
        Dictionary with lightrag_kwargs for RAGAnything initialization
        Returns empty dict if Qdrant disabled or unavailable (uses NanoVectorDB)
    
    Note:
        Collection names are auto-generated by LightRAG as:
        lightrag_vdb_{namespace}_{embedding_model}_{dimensions}d
        Example: lightrag_vdb_chunks_text_embedding_3_small_1536d
    """
    # Get configuration from environment or parameters
    if use_qdrant is None:
        use_qdrant_str = os.getenv("USE_QDRANT", "true").lower()
        use_qdrant = use_qdrant_str in ["true", "1", "yes"]

    if not use_qdrant:
        if verbose:
            print("✓ Using NanoVectorDB (default JSON storage)")
        return {}

    # Get Qdrant settings
    url = qdrant_url or os.getenv("QDRANT_URL", "http://localhost:6333")

    # Test connection
    if not test_qdrant_connection(url):
        print(f"\n⚠️  Qdrant not accessible at {url}")
        print("   Falling back to NanoVectorDB (default JSON storage)")
        print("   To use Qdrant, ensure it's running:")
        print("   - Run: scripts/qdrant/start_qdrant.sh")
        print("   - Or install first: scripts/qdrant/install_qdrant_local.sh")
        print("   - Or set USE_QDRANT=false in .env to disable this warning\n")
        return {}

    # Qdrant is available - use it
    if verbose:
        print(f"✓ Using Qdrant vector database")
        print(f"  URL: {url}")
        print(f"  Collections: Auto-generated by LightRAG")
        print(f"    - lightrag_vdb_chunks_{{model}}_{{dims}}d")
        print(f"    - lightrag_vdb_entities_{{model}}_{{dims}}d")
        print(f"    - lightrag_vdb_relationships_{{model}}_{{dims}}d")
        if multimodal:
            print("  Mode: Multimodal (text + image vectors)")

    # Base configuration
    # Note: collection_name is not used by LightRAG - it auto-generates names
    vector_db_kwargs = {
        "url": url
    }

    # Add multimodal configuration if specified
    if multimodal:
        from qdrant_client.http.models import Distance, VectorParams

        vector_db_kwargs["vector_params"] = {
            "text": VectorParams(size=1536, distance=Distance.COSINE),
            "image": VectorParams(size=512, distance=Distance.COSINE),
        }

    lightrag_kwargs = {
        "vector_storage": "QdrantVectorDBStorage",
        "vector_db_storage_cls_kwargs": vector_db_kwargs
    }

    return lightrag_kwargs


def get_qdrant_client(
    qdrant_url: Optional[str] = None
) -> Optional[Any]:
    """
    Get a Qdrant client instance for direct access.

    Args:
        qdrant_url: Override QDRANT_URL env var

    Returns:
        QdrantClient instance or None if unavailable
    """
    try:
        from qdrant_client import QdrantClient

        url = qdrant_url or os.getenv("QDRANT_URL", "http://localhost:6333")

        if not test_qdrant_connection(url):
            return None

        return QdrantClient(url=url)
    except ImportError:
        print("Error: qdrant-client not installed. Run: pip install qdrant-client")
        return None
    except Exception as e:
        print(f"Error creating Qdrant client: {e}")
        return None


if __name__ == "__main__":
    """Test configuration when run directly"""
    print("=" * 70)
    print("Qdrant Configuration Test")
    print("=" * 70)

    # Test environment variables
    print("\nEnvironment Variables:")
    print(f"  USE_QDRANT: {os.getenv('USE_QDRANT', 'not set (defaults to true)')}")
    print(f"  QDRANT_URL: {os.getenv('QDRANT_URL', 'not set (defaults to http://localhost:6333)')}")

    # Test configuration
    print("\nTesting configuration...")
    lightrag_kwargs = get_lightrag_kwargs(verbose=True)

    if lightrag_kwargs:
        print("\n✓ Qdrant configuration ready:")
        print(f"  {lightrag_kwargs}")
    else:
        print("\n✓ Using NanoVectorDB (default)")

    # Test client
    print("\nTesting Qdrant client...")
    client = get_qdrant_client()
    if client:
        try:
            collections = client.get_collections()
            print(f"✓ Connected! Found {len(collections.collections)} collection(s)")
            if collections.collections:
                for col in collections.collections:
                    print(f"  - {col.name}")
        except Exception as e:
            print(f"✗ Error: {e}")
    else:
        print("✗ Could not create client")

    print("\n" + "=" * 70)
